name: Check pull request
run-name: Build on pull request, branch '${{ github.head_ref }}'

on:
  pull_request:
    branches:
      - master

concurrency:
  group: check-pull-request-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  validate:
    name: Check
    uses: ./.github/workflows/sub-check.yml