name: Sub. Check code style

on:
  workflow_call:

jobs:

  php-cs-fixer:
    name: code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .php-cs-fixer.cache
          key: PhpCsFixer-${{ github.repository }}-${{ github.sha }}
          restore-keys: |
            PhpCsFixer-${{ github.repository }}-

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: -v --dry-run

  phpstan:
    name: code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json
        run: cd src && composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: Composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            Composer-${{ runner.os }}-

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs
          working_dir: src

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          version: 1.12.7
          php_version: 8.1
          memory_limit: 512M