name: Sub. Get WebTLO version

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      version:
        description: "Version of app"
        value: ${{ jobs.metadata.outputs.version }}
      sha:
        description: "Commit sha-hash"
        value: ${{ jobs.metadata.outputs.sha }}

jobs:
  metadata:
    name: get version
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      sha: ${{ steps.version.outputs.sha }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=ref,event=branch,prefix=-br-
            type=sha,prefix=

      - name: Get git ref version, sha
        id: version
        run: |
          suffix=${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          version=$( cd src && cat version.json | jq -r --arg V $suffix '.version + $V' )
          [ ${{ github.ref_type }} == 'tag' ] && version=${{ github.ref_name }}

          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "sha=${{ fromJSON(steps.meta.outputs.json).tags[1] }}" >> "$GITHUB_OUTPUT"

          echo "webtlo-version=$version, sha=$sha"